### ISSUE TITLE
Medium article code and github code mismatch.

### ISSUE THREAD

**Issue by harshitsinghai77** [izdwuut/fastapi-registration-tutorial#6]
https://levelup.gitconnected.com/handle-registration-in-fastapi-and-tortoise-orm-a673263bdba3

```
class CreateUser(pydantic.BaseModel):
    email: pydantic.EmailStr
    password: str
```

But in the Github:
https://github.com/izdwuut/fastapi-registration-tutorial/blob/main/models/users.py
```
class CreateUser(pydantic.BaseModel):
    email: pydantic.EmailStr
    password: pydantic.SecretStr
```

Kindly correct it in Medium article. Thanks.

**Comment by izdwuut** [comment]
Done. Thanks! It's quite difficult to track changes between the article and code repository. I did my best to update the article as I wrote code, but they can mismatch every now and then.
